#' @title Plot weighted averages between the independent and pooled models.
#' @export
#' @family plot
#' @description Plot weighted averages between
#'   the independent and pooled models.
#' @return A `ggplot` object
#' @inheritParams hb_plot_borrow
#' @param summary Data frame generated by [hb_summary_weighted()].
#' @param highlight_weights Numeric vector of values between 0 and 1,
#'   weights to highlight in bold blue in the plot.
#' @examples
#' if (!identical(Sys.getenv("HB_TEST", unset = ""), "")) {
#' set.seed(1)
#' data <- hb_sim_independent(n_continuous = 2)$data
#' data$group <- paste0("group_", data$group)
#' mcmc_pool <- hb_mcmc_pool(
#'   data,
#'   n_chains = 1,
#'   n_adapt = 100,
#'   n_warmup = 200,
#'   n_iterations = 200
#' )
#' mcmc_independent <- hb_mcmc_independent(
#'   data,
#'   n_chains = 1,
#'   n_adapt = 100,
#'   n_warmup = 200,
#'   n_iterations = 200
#' )
#' summary <- hb_summary_weighted(
#'   mcmc_pool = mcmc_pool,
#'   mcmc_independent = mcmc_independent,
#'   data = data,
#'   weights = c(0, 0.25, 0.5, 0.75, 1)
#' )
#' hb_plot_weighted(
#'   summary = summary,
#'   outcome = "response",
#'   highlight_weights = 0.5
#' )
#' }
hb_plot_weighted <- function(
  summary,
  outcome = c("response", "diff"),
  highlight_weights = numeric(0)
) {
  outcome <- match.arg(outcome)
  true(is.data.frame(summary))
  true(c("weight", "group") %in% colnames(summary))
  for (name in paste0(outcome, c("_mean", "_lower", "_upper"))) {
    true(name %in% colnames(summary))
  }
  true(highlight_weights, is.numeric(.), is.finite(.), . >= 0, . <= 1)
  out <- dplyr::select(
    summary,
    weight,
    group,
    group_label,
    tidyselect::starts_with(outcome)
  )
  out <- dplyr::select(
    summary,
    -tidyselect::ends_with(c("_mcse", "_sd", "_variance"))
  )
  out$group_label <- as.character(out$group_label)
  out$color <- ifelse(
    out$weight %in% highlight_weights,
    "blue",
    "black"
  )
  out$size <- 1 + 0.25 * (out$weight %in% highlight_weights)
  out <- out[!is.na(out[[paste0(outcome, "_mean")]]),, drop = FALSE] # nolint
  ggplot2::ggplot(out) +
    ggplot2::geom_point(
      ggplot2::aes_string(
        x = "weight",
        y = paste0(outcome, "_mean"),
        color = "color",
        size = "size"
      )
    ) +
    ggplot2::geom_errorbar(
      ggplot2::aes_string(
        x = "weight",
        ymin = paste0(outcome, "_lower"),
        ymax = paste0(outcome, "_upper"),
        color = "color",
        size = "size"
      )
    ) +
    ggplot2::xlab("Weight") +
    ggplot2::ylab("Posterior response") +
    ggplot2::facet_wrap(~group_label) +
    ggplot2::theme_gray(20) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = -90, vjust = 0.5),
      legend.position = "none"
    ) +
    ggplot2::scale_x_continuous(breaks = sort(unique(out$weight))) +
    ggplot2::scale_color_identity() +
    ggplot2::scale_size_identity()
}
